---
title: Eulercoder
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
markdown: kramdown
highlighter: rouge
paginate: 10
language: en-us
baseurl: http://eulercoder.me
description: A place for Eulercoder Community, all about internships, jobs, interviews
  and some motivation
cover: assets/images/blog-cover.jpg
logo: assets/images/blog-icon.png
logo_dark: assets/images/favicon.png
favicon: assets/images/favicon.png
production_url: http://eulercoder.me
source_url: https://github.com/Eulercoder/eulercoder.me
navigation: true
subscribers: true
twitter: vikesh002
facebook: eulercoder
disqus: true
disqus_shortname: vicky002
google_analytics: UA-45497633-11
permalink: "/:year/:month/:title/"
plugins:
- jekyll-paginate
- jekyll-feed
exclude:
- README.md
- Rakefile
- Gemfile
- Gemfile.lock
- changelog.md
- "*.Rmd"
- vendor
- ".travis.yml"
feed:
  path: feed.xml
safe: false
lsi: false
username: eulercoder
repo: eulercoder.github.io
branch: master
relative_source: "../eulercoder.github.io/"
destination: "../_site/"
